binbashar/le-ref-architecture-doc

docs/user-guide/base-workflow/leverage-cli/reference/terraform.md

* Add missing documentation for `apply` subcommand of the `terraform` command
* closes #91

Fix | Add `apply` subcommand to documentation

---

docs/user-guide/features/identities/gpg.md

* Describe the error that solves this workaround
* Describe the steps
* Reference docker installation link
* Recurring error with Mac users

add workaround for Mac users in section in gpg page

---

docs/user-guide/leverage-cli/reference/terraform.md
docs/user-guide/ref-architecture-ansible/workflow.md

* Added an example box for running TF commands inside shell
* Doc was not clear enough for specific use cases (running a TF command not supported by the CLI)
* Adding a specific example of a common issue where we need to use a TF command inside the shell
* There are many TF [commands](https://www.terraform.io/cli/commands) not supported by the CLI (as they are not used on a daily basis). The one used in the example is [force-unlock](https://www.terraform.io/cli/commands/force-unlock).

added example for terraform commands in the shell

---

docs/user-guide/leverage-cli/reference/terraform.md

* Add documentation for `--skip-documentation` flag in `terraform init` command.

Enahncement | Add --skip-validation flag documentation.

---

docs/user-guide/ref-architecture-aws/configs.md

- [Doc/ Replace legacy make commands for new leverage terraform ones + config for .tfvars](https://github.com/binbashar/le-ref-architecture-doc/commit/c2e652b53b95a2ce27c622373097b80d0d3bef0d) - @[exequielrafaela](https://github.com/binbashar/le-ref-architecture-doc/commits?author=exequielrafaela)
- https://github.com/binbashar/le-ref-architecture-doc/issues/113

Doc/ Replace legacy make commands for new leverage terraform ones 

---

docs/user-guide/ref-architecture-aws/tf-state-setup.md

- [Doc/ Replace legacy make commands for new leverage terraform ones + config for .tfvars](https://github.com/binbashar/le-ref-architecture-doc/commit/c2e652b53b95a2ce27c622373097b80d0d3bef0d) - @[exequielrafaela](https://github.com/binbashar/le-ref-architecture-doc/commits?author=exequielrafaela)
- closes https://github.com/binbashar/le-ref-architecture-doc/issues/113

Doc/ Replace legacy make commands for new leverage terraform

---

docs/user-guide/leverage-cli/reference/terraform.md

- [Doc/ leverage terraform import zsh scape chars](https://github.com/binbashar/le-ref-architecture-doc/commit/7669c0af8f0edd14ec7530726447cde27dda71c0) - @[exequielrafaela](https://github.com/binbashar/le-ref-architecture-doc/commits?author=exequielrafaela)
- Improve `leverage terraform import` command doc for zsh users

Doc/ leverage terraform import zsh scape chars

---

docs/first-steps/aws-account-setup.md

- [Update aws-account-setup.md](https://github.com/binbashar/le-ref-architecture-doc/commit/ff0f6f7be9f16906a5e8321989a264156edeaf9b) 
- updating user and keys generation paragraph to directly reference leverage user-guide internal doc to make the doc simpler and more understandable - @[exequielrafaela](https://github.com/binbashar/le-ref-architecture-doc/commits?author=exequielrafaela)
- Simplifying dev experience while doing this init setup, avoiding routing the user to the official doc which is longer and more complex.
- Consider that in the internal doc (new link) we still keep the official aws docs links.

Doc | Update aws-account-setup.md

---

docs/work-with-us/roadmap/leverage-cli/overview.md

2022 roadmap link was leading to 2023 roadmap. The link was fixed.
A new line was added with 2023 roadmap reference. Is this correct? Should we have the 2023 roadmap here as of 2022/08?
* In the referred web page, the link leading to the 2022 Roadmap was fixed. 
* A link for the 2023 Roadmap was added.
* The link was wrong, stating the 2022 Roadmap name but leading to the 2023 one.
* Web page where the link is: https://leverage.binbash.com.ar/work-with-us/roadmap/leverage-cli/overview/
* Link to the 2023 Roadmap: https://binbash.atlassian.net/wiki/external/1934983197/MGM3ZTljOTAzODhlNDVjZjhlYTk5MmNhYzc5NTk1ZDU?atlOrigin=eyJpIjoiZGUxMmRiMzE4ZmQzNDEyZThiYWMzNGU3MmIzOWE2ODciLCJwIjoiYyJ9
* Link to the 2022 Roadmap: https://binbash.atlassian.net/wiki/external/2196799489/NDZmMzNmMjE5Y2FmNDFjOGFk …

Fix link to roadmap

---

docs/first-steps/management-account.md
docs/first-steps/security-and-shared-accounts.md
docs/user-guide/ref-architecture-aws/tf-state-workflow.md

Added --skip-validation to <leverage terraform init> lines in documentation when there is no S3 set yet.
* Description on whether to add this flag added to these files:
* docs/first-steps/management-account.md
* docs/first-steps/security-and-shared-accounts.md
* docs/user-guide/ref-architecture-aws/tf-state-workflow.md
* When `leverage terraform init` is run for the very first time, there is no S3 bucket created to be set as a backend. The command as it is will fail.
* The flag `--skip-validation` allows to run the command, creating the bucket.
* After it is created, the backend can be set and the `init` command can be run with no errors.
* Close #125 
* URLs belonging to modified files:
* https://leverage.binbash.com.ar/first-steps/management-account/#terraform-backend-layer
* …

ISSUE-125 | add --skip-validation flag to documentation

---

docs/first-steps/post-deployment.md

* Add new step to avoid errors with MFA configuration 
* Update information about the correct steps for this section
Leverage Documentation:  first-steps -- > post-deployment 
[https://leverage.binbash.com.ar/first-steps/post-deployment/](https://leverage.binbash.com.ar/first-steps/post-deployment/)
Following @angelofenoglio 's recomendation:
In order to skip errors during the last steps of the first landing zone realted to the configuration of the MFA devices for the aws profiles, we need to follow this steps
1. Create new passwords for users in **Management** and **Security** accounts
2. Configure the new credentilas running `leverage credentials configure`  **without** the flag `--fetch-mfa-device `
3. Enable MFA and change the aws profile names
4. Run again  `leverage credentials …

Doc | Post-deployment section: add new step for --fetch-mfa-device 

---

docs/first-steps/post-deployment.md

* For this this step it must say:  Change output sensitive argument from `true` to `false`, to be able to show the encrypted passwd.
*  But then we also need add some comment to change it back again once we get the tmp passwd.
* I think another better option, is to directly run the output with the --json flag  like this :
`leverage terraform output --json `
This command shows you the value without the need for any code changes .
- Documentation:  first-steps -- > post-deployment 
[https://leverage.binbash.com.ar/first-steps/post-deployment/#get-the-temporary-password-to-access-aws-console
](https://leverage.binbash.com.ar/first-steps/post-deployment/#get-the-temporary-password-to-access-aws-console
)

Doc | Post-deployment section: change method to get temp password 

---

docs/user-guide/leverage-cli/install-leverage-cli.md
docs/user-guide/leverage-cli/reference/basic-features.md
docs/user-guide/leverage-cli/reference/kubectl.md
mkdocs.yml

Adding the documentation for the new `kubectl` wrapper command.
New required toolbox image: https://github.com/binbashar/le-docker-leverage-toolbox/pull/43
Feature: https://github.com/binbashar/leverage/pull/172

Kubectl command documentation

---

docs/first-steps/post-deployment.md
docs/user-guide/leverage-cli/reference/private-repos.md
docs/user-guide/leverage-cli/shell.md
mkdocs.yml

* Information regarding the `SSH-Agent` usage was added under `user-guide/leverage-cli/reference/private-repos/`.
* To clarify how Leverage CLI works regarding the SSH accessed private repositories and help the users to provide the correct SSH keys in order to be able to clone them.
* related to https://github.com/binbashar/leverage/issues/173
* related to https://github.com/binbashar/leverage/pull/174

ISSUE-173 added documentation on ssh-agent usage

---

docs/assets/stylesheets/extra.css
material/overrides/home-es.html
material/overrides/home.html

* Increase size of footer social media icons.
* Resolves the mobile display problem that was detected by Search Console, where buttons were small and too close together.
* Improve SEO positioning and resolve mobile display issues.
* Task BBL-105 | Issues fix at binbash.com.ar
* Open Google Chrome ->  Developer tools->  Device toolbar icon -> Select  mobile style-> Choose device "iPhone XR"

BBL-105 | Fix: increase size footer social media icons

---

docs/user-guide/ref-architecture-aws/references.md

- [Fix links at references.md](https://github.com/binbashar/le-ref-architecture-doc/commit/e077eb7c01b8d0118a21c01c84b320ea959e3b9b) - @[exequielrafaela](https://github.com/binbashar/le-ref-architecture-doc/commits?author=exequielrafaela)
* Broken links at this section

Fix | broken links at references.md

---

CNAME
CODE-OF-CONDUCT.md
Makefile
README.md
docs/CNAME
docs/try-leverage/add-aws-accounts.md
docs/user-guide/ref-architecture-aws/features/identities/credentials-vault.md
docs/work-with-us/archived/contact.md.back
docs/work-with-us/careers.md
docs/work-with-us/faqs.md
docs/work-with-us/releases/versions-compatibility-matrix.md
docs/work-with-us/support.md
material/overrides/home-es.html
material/overrides/home.html
mkdocs.yml

- [updating domain from binbash.com.ar to binbash.co](https://github.com/binbashar/le-ref-architecture-doc/commit/d0b223a1cd764627daa44dfb5f6d96471fe3e569) - @[exequielrafaela](https://github.com/binbashar/le-ref-architecture-doc/commits?author=exequielrafaela)
* [LEWW-130 | Configure binbash.co](https://trello.com/c/Zve2yEql/130-leww-130-configure-binbashco)
* Sitemap.xml generation for proper google analytics and search console integrations

Doc | updating domain from binbash.com.ar to binbash.co

---

CNAME
CODE-OF-CONDUCT.md
Makefile
README.md
docs/CNAME
docs/try-leverage/add-aws-accounts.md
docs/user-guide/ref-architecture-aws/features/identities/credentials-vault.md
docs/user-guide/ref-architecture-aws/features/organization/configuration.md
docs/work-with-us/archived/contact.md.back
docs/work-with-us/careers.md
docs/work-with-us/faqs.md
docs/work-with-us/releases/versions-compatibility-matrix.md
docs/work-with-us/support.md
material/overrides/home-es.html
material/overrides/home.html
mkdocs.yml

Fix | fixing typo

---

docs/try-leverage/aws-account-setup.md
docs/try-leverage/leverage-project-setup.md

Suggest to use us-east-2 in the example.
Because it is cheaper.
- https://github.com/binbashar/le-ref-architecture-doc/issues/186

Link to best region analysis

---

Makefile
docs/user-guide/ref-architecture-eks/overview.md
material/overrides/home-es.html
material/overrides/home.html

* Updating material mkdocs to latest version

Enhancement | Updating material mkdocs to latest version

---

docs/user-guide/leverage-cli/installation.md
docs/user-guide/leverage-cli/private-repositories.md
docs/user-guide/troubleshooting/general.md

* Describe high-level what changed as a result of these commits (i.e. in plain-english, what do these changes mean?)
* Use bullet points to be concise and to the point.
* Provide the justifications for the changes (e.g. business case). 
* Describe why these changes were made (e.g. why do these commits fix the problem?)
* Use bullet points to be concise and to the point.
https://github.com/binbashar/leverage/issues/173
https://github.com/binbashar/leverage/pull/213/

[BB-173] SSH config folder documentation

---

docs/user-guide/ref-architecture-aws/features/network/network-nacl.md
mkdocs.yml

-  Add new page for Network ACLS in the user guide section
- Documentation:  user-guide/ref-architecture-aws/features/network/
- Closes https://github.com/binbashar/le-tf-infra-aws-template/issues/36

Doc |  User-guide: Add Nework ACL section

---

docs/user-guide/ref-architecture-aws/configuration.md
docs/user-guide/ref-architecture-aws/credentials.md
docs/user-guide/ref-architecture-eks/credentials.md
mkdocs.yml

* Create index page for credentials under AWS and EKS reference architectures
* Also briefly update AWS configuration page to link to the new pages
* Since we support multiple ways to handle credentials, having an entry page makes sense.
* Issue: #122

Create index page for credentials under AWS and EKS reference architectures

---

docs/user-guide/troubleshooting/general.md

In Linux environment it is recommended to install Docker in rootless mode. docker-py looks by default Docker at `unix:///var/run/docker.sock` unless DOCKER_HOME environment is specified. While, the [Docker installation notes for Rootless mode](https://docs.docker.com/engine/security/rootless/) clearly advise to set it, if overlooked, it leads to problem connecting to Docker:
```
[10:40:04.464] ERROR    Docker daemon doesn't seem to be responding. Please check it is up and running correctly before re-running the command.
```
* Helps people when the issue happen. 
* https://docs.docker.com/engine/security/rootless/

doc: Add troubleshooting note about rootless Docker

---

docs/try-leverage/aws-account-setup.md

* The form that the management account should have was highlighted.
* As per the @marcosgacosta 's report it clarifies the initial Landing Zone creation process

ENHANCEMENT | improved the doc on what is the correct name for management acc

---

docs/user-guide/ref-architecture-aws/credentials.md
docs/user-guide/ref-architecture-eks/credentials.md

* Fix wrong links in Credentials page
* They were set wrong
* #122

Fix credentials links

---

docs/user-guide/cookbooks/argocd-external-cluster.md

* Adde notes on how to deploy multiple cluster wide ArgoCD instances in the same cluster.
* If the step stated in the note is not done then the different instances will conflict.
* https://github.com/argoproj/argo-cd/issues/18965
Please include a screenshot of the pages that you modified to help reviewers. If you are using Chrome, you can follow the instructions below to easily take a full screenshot of the entire page:
1. Right click the page and open the inspector.
2. In the top left of Chrome Inspector you'll see a little phone icon whose tooltip shows "Toggle device emulation".
3. Hit that and a new black bar will appear on the top of the webpage.
4. In the black bar you can pick the dimensions of the screen you want to stimulate -- Since the documentation uses a responsive layout, …

FIX added notes on multiple argo cd instances in the same cluster

---

docs/user-guide/cookbooks/argocd-external-cluster.md

* quick fix to a command line example
* it was pasted with escaped chars when no escape is needed
(removing backslashes previous to quotes)

FIX quick fix to a command line example

---

docs/user-guide/cookbooks/index.md

* Fixed link in Cookbooks
* It is failing
N/A
Please include a screenshot of the pages that you modified to help reviewers. If you are using Chrome, you can follow the instructions below to easily take a full screenshot of the entire page:
1. Right click the page and open the inspector.
2. In the top left of Chrome Inspector you'll see a little phone icon whose tooltip shows "Toggle device emulation".
3. Hit that and a new black bar will appear on the top of the webpage.
4. In the black bar you can pick the dimensions of the screen you want to stimulate -- Since the documentation uses a responsive layout, you'll probably want to set a wide enough value on the width field, e.g. 1024x768, then the height is not as important.
5. In top right of black bar is three dots, in that menu you can …

Fixed VPN link in cookbooks

---

docs/user-guide/cookbooks/index.md
docs/user-guide/cookbooks/k8s.keda.md
docs/user-guide/cookbooks/k8s.md
mkdocs.yml

* Added documentation on how to create an EKS cluster with Leverage
* Added documentation on how to use (in a basic way) KEDA
* To have more cookbooks for the eng to lear how to do different tasks
N/A
Please include a screenshot of the pages that you modified to help reviewers. If you are using Chrome, you can follow the instructions below to easily take a full screenshot of the entire page:
1. Right click the page and open the inspector.
2. In the top left of Chrome Inspector you'll see a little phone icon whose tooltip shows "Toggle device emulation".
3. Hit that and a new black bar will appear on the top of the webpage.
4. In the black bar you can pick the dimensions of the screen you want to stimulate -- Since the documentation uses a responsive layout, you'll probably want to set a …

Added documentation on EKS and KEDA

---

docs/user-guide/leverage-cli/reference/terraform.md
docs/user-guide/troubleshooting/general.md

* Added documentation on how to escape chars using the command line for resource arrays.
* It is not a common case, but it worth to be documented.
N/A
Please include a screenshot of the pages that you modified to help reviewers. If you are using Chrome, you can follow the instructions below to easily take a full screenshot of the entire page:
1. Right click the page and open the inspector.
2. In the top left of Chrome Inspector you'll see a little phone icon whose tooltip shows "Toggle device emulation".
3. Hit that and a new black bar will appear on the top of the webpage.
4. In the black bar you can pick the dimensions of the screen you want to stimulate -- Since the documentation uses a responsive layout, you'll probably want to set a wide enough value on the width field, e.g. …

Added documentation on how to troubleshoot the case of scaping chars in CLI

---

docs/user-guide/cookbooks/VPN-server/index.md

* Add AWS VPN Endpoint as an alternative for VPN
* Provide an alternative to Pritunl

add aws vpn endpoint

---

docs/user-guide/ref-architecture-eks/overview.md

* Remove link to base EKS cluster
* We only have the DemoApps EKS cluster now.

Remove link to base EKS cluster

---

docs/user-guide/leverage-cli/basic-features.md
docs/user-guide/leverage-cli/installation.md
docs/user-guide/leverage-cli/reference/run.md

* Move custom tasks flags documentation from basic usage page to the run command page.
* Update documentation for verbose output to reflect current state.

Doc | Update custom tasks flags documentation
