docs/CNAME
- @exequielrafaela - BBL-119 adding CNAME file for gp custom domain - 694f17b
=> BBL-119 | adding CNAME file for gp custom domain

.chglog/CHANGELOG.tpl.md, .chglog/config.yml, .circleci/config.yml, .github/CODEOWNERS, .github/ISSUE_TEMPLATE/bug_report.md, .github/ISSUE_TEMPLATE/config.yml, .github/ISSUE_TEMPLATE/feature_request.md, .github/PULL_REQUEST_TEMPLATE.md, LICENSE.md, Makefile, Makefile.release, README.md
- @exequielrafaela - BBL-119 small fix in README.md link - 1ad451d
- @exequielrafaela - BBL-119 re ading std structure files to the repo - 452b35f
=> Bbl 119 | mkdocs gh updates

.circleci/config.yml, Makefile
- @exequielrafaela - BBL-119 updating Makefile cmd to install mkdocs - 4e92c3f
=> BBL-119 updating Makefile cmd to install mkdocs

Makefile
- @exequielrafaela - BBL-119 Adding pip install markdown package - 7383d8e
=> BBL-119 Adding pip install markdown package

material/overrides/home.html
- @exequielrafaela - BBL-119 updating landing link to point to the support section - 00e133b
=> BBL-119 updating landing link to point to the support section

material/overrides/home.html
- @exequielrafaela - BBL-19 reviewing landing text grammar - 09cb7f0
- @exequielrafaela - BBL-19 improving landing text - 4921125
=> Bbl 119 mkdocs gh updates

.circleci/config.yml, mkdocs.yml
- @exequielrafaela - BBL-19 integrating Google Analytics - edaa555
- @exequielrafaela - BBL-19 since how-it-works its complete we're releasing v0.1.0 minor ver - d51ae7d
=> BBL-19 | ref arch doc content updates

.circleci/config.yml, docs/user-guide/base-configuration/overview.md, docs/user-guide/compute/k8s-kops.md, docs/user-guide/monitoring/apm.md, docs/user-guide/network/dns.md
- @exequielrafaela - BBL-19 user-guide/network/dns updated - d2177a7
- @exequielrafaela - BBL-19 user-guide/base-configuration/overview adding pre-reqs - 3b08f3b
* Leverage user-guide base config pre-reqs added
* Leverage user-guide **Route53 DNS hosted zones** section completion
- pre-requisites
- example "Steps"
- Migrated AWS Route53 Hosted Zones between AWS Accounts
=> BBL-19 | user-guide/network/dns updated

docs/user-guide/base-configuration/overview.md, docs/user-guide/organization/accounts.md, docs/user-guide/organization/organization.md, mkdocs.yml
- @exequielrafaela - BBL-19 user-guide/organizations email pre-req doc added - d71da33
- User guide organizations email pre-requisite was not correctly explained.
=> BBL-19 user-guide/organizations email pre-req doc added

docs/user-guide/base-configuration/overview.md, docs/user-guide/identities/gpg.md, docs/user-guide/identities/identities.md, mkdocs.yml
- @exequielrafaela - BBL-19 | user-guide/identities completed - 769e9d1
- @exequielrafaela  - BBL-19 small sintaxt improvement - 0c47732
- @exequielrafaela - BBL-19 minor adjustments to user-guide identities files - b33a9c5
- Updating pre-req deps
- Adding medium to social nets.
=> BBL-19 | user-guide/identities completed

Makefile, docs/welcome.md, material/overrides/home.html, material/overrides/main.html
- @exequielrafaela - BBL-445 | adding sudo to make apply-rclone to fix permissions denied error - 536078e
- @exequielrafaela - BBL-455 | minor landing adjustements - 8576e3d
- Welcome page updated
=> Feature/BBL-455 | 1st steps section

Makefile, mkdocs.yml
- @exequielrafaela - BIZDEV-26 | testing new material mkdocs multi-language experimental feature - ccc936b
- @exequielrafaela - BBL-192 | updating material mkdocs via latest ver in makefilelib - fde3587
=> Feature/BIZDEV-26 | material mkdocs version upgradde

docs/how-it-works/code-library/code-library-forks.md, mkdocs.yml
- @exequielrafaela - BIZDEV-26 | Adding how it works code library forks workflow sub-section - f011353
- Clear out the Open Source fork collaboration workflow.
=> BIZDEV-26 | Adding how it works code library forks workflow sub-section

docs/how-it-works/monitoring/logs.md, docs/how-it-works/monitoring/tracing.md, docs/how-it-works/network/vpc-traffic-out.md, material/overrides/main.html, mkdocs.yml
- @exequielrafaela - BBL-488 | Adding ES solutions comparison + VPC outbound traffic control solutions comparison + adding Ganalytics domain verification tag - fca1c82
- Adding google domain verif
- Adding comparison for ES centralized log solutions.
- Adding comparison for VPC Outbound traffic control
=> BBL-488 | Adding ES solutions comparison + VPC outbound traffic control

.circleci/config.yml, .github/release-drafter.yml, .github/workflows/release-management.yml, docs/how-it-works/organization/organization.md, docs/work-with-us/team.md, docs/work-with-us/testimonials.md, material/overrides/home.html
- @exequielrafaela - BBL-192 | updating release mgmt automation to GH actions - ea283aa
- @exequielrafaela - BBL-192 | work with us and how it works orgs sections updated + landing update - 7a886e7
## Why?
- Organizations, and how it works updates
- Landing new testimonial
- Release mgmt improvement
=> Feature/BBL-192 | landing update + release mgmt to GH actions

docs/work-with-us/testimonials.md, material/overrides/home-es.html, material/overrides/home.html, material/overrides/main-styles.html, material/overrides/subscription-plans.html, material/overrides/team.html
- @exequielrafaela - LEWW-69 | Updating testimonial - 0d6b942
- @exequielrafaela - LEWW-69 | temporary removing Braintrust section from landing - 117fb64
- @exequielrafaela - LEWW-69 | Adjusting max with 1600px resolution responsiveness + minor section content updates - db72507
- https://trello.com/c/746buoLZ/69-leww-69-landing-release-mgmt
=> Feature/LEWW-69 | code structure

docs/how-it-works/costs/costs.md, docs/work-with-us/faqs.md, docs/work-with-us/index.md, material/overrides/subscription-plans.html, mkdocs.yml
- @exequielrafaela - LEWW-71 | several updates and fixes - work with us and subscription - 8916c00
=> LEWW-71 | several updates and fixes - work with us and subscription

docs/work-with-us/faqs.md, docs/work-with-us/index.md, material/overrides/home.html
## What?
- @exequielrafaela - LEWW-71 | updating landing header + work with us sintaxt fixes - ef3a47c
=> LEWW-71 | updating landing header + work with us sintaxt fixes

.circleci/config.yml, docs/first-steps/introduction.md, material/overrides/work-with-us/leverage-vs-competition.html
### Commits on Sep 29, 2021
- @exequielrafaela - first step section intro figure link fixed - 378bd57
- @exequielrafaela - fixing deploy command in circleci config file - 4105113
- @exequielrafaela - fixing number of repos in leverage vs competition section - 65e9c06
- minor content fixes
- fixing circleci deployment pipeline step
=> Fix/first steps intro fig link + circleci deployment command

docs/first-steps/leverage-project-setup.md, docs/first-steps/management-account.md, docs/first-steps/post-deployment.md, docs/first-steps/security-and-shared-accounts.md, docs/user-guide/base-workflow/leverage-cli/reference/credentials.md, docs/user-guide/base-workflow/leverage-cli/reference/terraform.md
* Update First-Steps guide to reflect the current implementation of the `leverage credential` command, as well as said command documentation itself.
* Small updates in `leverage terraform` command documentation.
* https://github.com/binbashar/leverage/issues/68
=> Enhancement | Update first steps guide and credentials command documentation

Makefile, mkdocs.yml
- updating to latest mkdocs version + tab feature fix - @exequielrafaela
=> fix/ updating to latest mkdocs version + tab feature fix

docs/first-steps/leverage-project-setup.md, docs/first-steps/post-deployment.md, docs/user-guide/features/sso/sso.md, docs/user-guide/leverage-cli/reference/credentials.md, docs/user-guide/leverage-cli/reference/terraform.md, docs/user-guide/leverage-cli/shell.md
* Reworded part of SSO documentation for clarity
* Add documentation regarding the `terraform validate-layout` command
* Updated `credentials configure` command with the newest flag `--fetch-mfa-device`
* Updated documentation for the terraform shell environment
=> Feature | Update `terraform shell` and `credentials documentation`

.circleci/config.yml
=> Fix | Update circleci image

docs/user-guide/leverage-cli/install-leverage-cli.md, docs/user-guide/leverage-cli/reference/basic-features.md, docs/user-guide/leverage-cli/reference/terraform.md, docs/user-guide/leverage-cli/reference/terraform/layers.md, docs/user-guide/leverage-cli/reference/tfautomv.md, docs/user-guide/ref-architecture-aws/workflow.md, docs/work-with-us/releases/versions-compatibility-matrix.md, mkdocs.yml
* Notes on Leverage CLI release 1.9.0
* We need to document all the changes and new features in the reference documentation.
n/a
=> Issue 152 cli v1.9.0 release update

docs/user-guide/leverage-cli/install-leverage-cli.md
* add update procedure
* It was requested to have this procedure stated in the doc
* closes https://github.com/binbashar/le-ref-architecture-doc/issues/147
=> ISSUE-147 Added update procedure

docs/user-guide/ref-architecture-aws/features/sso/configuration.md
* Fix broken link
* Link was broken
N/A
=> Fix broken link

docs/try-leverage/add-aws-accounts.md, docs/try-leverage/post-deployment.md
Fix broken link
Link was broken
=> fixing broken links on documentation

docs/assets/stylesheets/extra.css, docs/user-guide/ref-architecture-eks/cluster-upgrade.md, docs/user-guide/ref-architecture-eks/overview.md, material/overrides/home-es.html, material/overrides/home.html
* Add new html class to hide content for mobile version. 
* Update footer style for homepage .
* Add link with the aws procedure to plan an EKS upgrade.
* Improve SEO for mobile version.
* Update Leverage documentation content.
* Task BBL-105
* Slack message: https://binbashar.slack.com/archives/GG0PJ78J3/p1683575685115409
=> BBL-105 | Fix: improve seo for mobile version

docs/user-guide/ref-architecture-eks/overview.md, material/overrides/home-es.html, material/overrides/home.html
- [fixing old hyperlinks with updated ones](https://github.com/binbashar/le-ref-architecture-doc/commit/645cf362e3307b5a6f2b8fa9a7a0a94a846d8556) - @[exequielrafaela](https://github.com/binbashar/le-ref-architecture-doc/commits?author=exequielrafaela)
- Broken links have been reported
=> Fix | replace old hyperlinks with updated ones

docs/try-leverage/leverage-project-setup.md, docs/try-leverage/management-account.md
Update text:
* SSO layer configuration information about AWS regions.
* How to configurate correctly poyect_name field.
* Clarify information about configuration procedure
* 
* closes issue #186, Bug 2 and Bug 4
=> ISSUE-186(doc): clarify SSO layer and project_name config information

docs/concepts/our-tech-stack.md
=> FIX/ fixed AIM title to IAM

docs/try-leverage/leverage-project-setup.md
* Wrong word in text 
* here: https://leverage.binbash.co/try-leverage/leverage-project-setup/#:~:text=Next%2C%20you%20will%20orchestrate%20de%20first%20and%20main%20account%20of%20the%20project%2C%20the%20management%20account
* closes PR #171
=> Fix | Update typo in leverage-project-setup.md

docs/user-guide/playbooks/VPN-with-no-LandingZone.md, docs/user-guide/playbooks/index.md, docs/user-guide/playbooks/schedule-start-stop-ec2.md, mkdocs.yml
=> FEATURE/ added playbook section

docs/user-guide/playbooks/VPC-with-no-LandingZone.md, docs/user-guide/playbooks/index.md, mkdocs.yml
* The title said VPN while the post was about VPC
* To have the correct title.
=> FIX/ fixed wrong title

docs/user-guide/leverage-cli/basic-features.md, docs/user-guide/leverage-cli/reference/shell.md, docs/user-guide/leverage-cli/reference/terraform.md, mkdocs.yml
Document new `shell` command.
Update `terraform` doc showing mount/env-vars support.
=> [BB-233] shell section + terraform updates

docs/user-guide/ref-architecture-eks/cluster-upgrade.md
* Update EKS cluster upgrade guide with relevant information after performing v1.25 and v1.26 upgrades.
* Keep the docs relevant and useful to the team and the community.
=> Docs | Update EKS cluster upgrade docs

docs/user-guide/ref-architecture-aws/features/ssm/ssm.md, mkdocs.yml
- Added comprehensive documentation on setting up and managing AWS SSM sessions using the Leverage CLI integrated with AWS Single Sign-On (SSO).
- Included detailed step-by-step guides, command syntax examples, and troubleshooting tips to ensure users can easily understand and implement SSM session management.
- **Enhance User Knowledge:** The documentation aims to provide users with all the necessary information to set up and manage SSM sessions using Leverage CLI and SSO, making the process straightforward and accessible.
- **Support Best Practices:** By detailing best practices and typical setups, the documentation helps users avoid common pitfalls and promotes more secure and efficient use of AWS resources.
- **Improve Accessibility:** Making this information readily available and …
=> Feature | AWS SSM start-session integration with leverage + SSO

.github/PULL_REQUEST_TEMPLATE.md
* Updated PR template to add a section that suggests to include screenshots and instructions on how to take them
* Screenshots help reviewers
N/A
=> Update PR template to add screenshot notes

docs/user-guide/ref-architecture-eks/cluster-upgrade.md
* Update EKS cluster upgrade guide with relevant information after performing upgrade to v1.27.
* Keep the docs relevant and useful to the team and the community.
=>   Docs | Update EKS cluster upgrade docs

docs/user-guide/cookbooks/VPN-server.md, docs/user-guide/cookbooks/index.md, mkdocs.yml
* playbook for vpn added
* to create a document on how to create a VPN pritunl server
=> FEATURE/ added VPN document

material/overrides/home-es.html
* Change a link to the right path because it doesn't exist
* The website is giving 404 on the current link
=> fix wrong link
